#for Azure pipeline
name: TRANSLATOR,test,trigger

#啟動的條件
on:
  push:
      branch:
        -main
  pull-request:
      branch:
        -main

#啟動之後需要執行的工作
job:
  build-and-push:
    runs-on: ubuntu-latest (windows-latest) | Ubuntu-'20.2'
    steps:
    -
    #階層式工作執行，建議根據執行工作做排序
    name: check-out
    uses: actions/checkout@v2
    -
    #保持docker image 與external github 同步
    name: set up Docker builder
    uses: actions/set-up builder-action@Login
    -
    name: Login to Github
    uses: docker/login-action@v1
    with:
      register: ghcr.io
      username: ${{github.repository_owner}}
      password: ${{secret.GHRC_TOKEN}}

    name: Build and push
    uses: docker/build-push-action@v2
    with:
      context:
      file: ./Dockerfile
      push: true
      tags:
        ghcr.io/sggmark/Translator-Bot: latest

# Use WebAPPService
app: user-authentication
port: 6000
version: 2


      
    






    
    
    
